import PDFDocument from 'pdfkit';

const BRAND_BLUE   = '#137fec';
const BRAND_DARK   = '#0d1b2a';
const BODY_TEXT    = '#2d3748';
const MUTED        = '#718096';
const BORDER_LIGHT = '#e2e8f0';

/**
 * Generates a branded PDF for a clinical report.
 * Returns a Buffer containing the PDF bytes.
 *
 * @param {string} reportText  - Plain text report content
 * @param {object} meta        - { templateName, patientName, doctorName, clinicName,
 *                                clinicTagline, clinicAddress, clinicPhone, clinicEmail }
 */
export function generateReportPdf(reportText, meta = {}) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });

    doc.on('data',  chunk => chunks.push(chunk));
    doc.on('end',   ()    => resolve(Buffer.concat(chunks)));
    doc.on('error', err   => reject(err));

    const PW = doc.page.width;
    const ML = doc.page.margins.left;
    const MR = doc.page.margins.right;
    const contentWidth = PW - ML - MR;

    // ── Header band ──────────────────────────────────────────────────────────
    doc.rect(0, 0, PW, 90).fill(BRAND_BLUE);

    const clinicName = meta.clinicName || 'Dental Clinic';
    doc.fillColor('white')
       .fontSize(20).font('Helvetica-Bold')
       .text(clinicName, ML, 22, { width: contentWidth * 0.7 });

    if (meta.clinicTagline) {
      doc.fontSize(10).font('Helvetica')
         .text(meta.clinicTagline, ML, 48, { width: contentWidth * 0.7 });
    }

    // Generated by badge (top right)
    doc.fontSize(8).font('Helvetica')
       .text('Generated by Molaris AI', PW - MR - 130, 36, { width: 120, align: 'right' });

    // ── Patient info card ─────────────────────────────────────────────────────
    const cardY = 105;
    doc.rect(ML, cardY, contentWidth, 72).fill('#f7fafc').stroke(BORDER_LIGHT);

    const labelX = ML + 14;
    const valueX = ML + 105;
    const col2LabelX = ML + contentWidth / 2 + 10;
    const col2ValueX = col2LabelX + 90;

    doc.fillColor(MUTED).fontSize(8).font('Helvetica-Bold');
    doc.text('PATIENT',       labelX,       cardY + 12);
    doc.text('REPORT TYPE',   labelX,       cardY + 38);
    doc.text('DOCTOR',        col2LabelX,   cardY + 12);
    doc.text('DATE',          col2LabelX,   cardY + 38);

    doc.fillColor(BRAND_DARK).fontSize(10).font('Helvetica-Bold');
    doc.text(meta.patientName || '—', valueX, cardY + 10, { width: contentWidth / 2 - 120 });

    doc.font('Helvetica').fontSize(10).fillColor(BODY_TEXT);
    doc.text(meta.templateName || 'Clinical Report', valueX, cardY + 36, { width: contentWidth / 2 - 120 });
    doc.text(meta.doctorName   || '—',              col2ValueX, cardY + 10);
    doc.text(
      new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }),
      col2ValueX, cardY + 36,
    );

    // ── Divider + section title ───────────────────────────────────────────────
    const bodyY = cardY + 88;
    doc.moveTo(ML, bodyY).lineTo(ML + contentWidth, bodyY).stroke(BRAND_BLUE);

    doc.fillColor(BRAND_BLUE).fontSize(10).font('Helvetica-Bold')
       .text(meta.templateName || 'Clinical Report', ML, bodyY + 10);

    // ── Report body ───────────────────────────────────────────────────────────
    const textY = bodyY + 30;
    doc.fillColor(BODY_TEXT).fontSize(10).font('Helvetica')
       .text(reportText || '', ML, textY, {
         width: contentWidth,
         lineGap: 3,
         paragraphGap: 6,
       });

    // ── Footer (on every page) ────────────────────────────────────────────────
    const pageCount = doc.bufferedPageRange().count;
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);
      const footerY = doc.page.height - 40;
      doc.moveTo(ML, footerY - 6).lineTo(ML + contentWidth, footerY - 6).stroke(BORDER_LIGHT);

      const footerParts = [
        meta.clinicName,
        meta.clinicPhone,
        meta.clinicEmail,
        meta.clinicAddress,
      ].filter(Boolean).join('  ·  ');

      doc.fillColor(MUTED).fontSize(8).font('Helvetica')
         .text(footerParts, ML, footerY, { width: contentWidth - 60 });

      doc.text(`Page ${i + 1} of ${pageCount}`, ML, footerY, { width: contentWidth, align: 'right' });
    }

    doc.end();
  });
}
